name: dart_get_up
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  meta: ^1.8.0
  path: ^1.8.0
  riverpod: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lints: ^2.0.0
  test: ^1.16.0
